export interface CompanyEntry {
  name: string;
  ticker: string;
  domain: string;
}

export const companies: CompanyEntry[] = [
  { name: "Apple", ticker: "AAPL", domain: "apple.com" },
  { name: "Microsoft", ticker: "MSFT", domain: "microsoft.com" },
  { name: "Amazon", ticker: "AMZN", domain: "amazon.com" },
  { name: "Alphabet", ticker: "GOOGL", domain: "google.com" },
  { name: "Meta Platforms", ticker: "META", domain: "meta.com" },
  { name: "NVIDIA", ticker: "NVDA", domain: "nvidia.com" },
  { name: "Tesla", ticker: "TSLA", domain: "tesla.com" },
  { name: "Berkshire Hathaway", ticker: "BRK.B", domain: "berkshirehathaway.com" },
  { name: "JPMorgan Chase", ticker: "JPM", domain: "jpmorganchase.com" },
  { name: "Johnson & Johnson", ticker: "JNJ", domain: "jnj.com" },
  { name: "Visa", ticker: "V", domain: "visa.com" },
  { name: "UnitedHealth Group", ticker: "UNH", domain: "unitedhealthgroup.com" },
  { name: "Procter & Gamble", ticker: "PG", domain: "pg.com" },
  { name: "Mastercard", ticker: "MA", domain: "mastercard.com" },
  { name: "Eli Lilly", ticker: "LLY", domain: "lilly.com" },
  { name: "Home Depot", ticker: "HD", domain: "homedepot.com" },
  { name: "Chevron", ticker: "CVX", domain: "chevron.com" },
  { name: "Merck", ticker: "MRK", domain: "merck.com" },
  { name: "AbbVie", ticker: "ABBV", domain: "abbvie.com" },
  { name: "Costco", ticker: "COST", domain: "costco.com" },
  { name: "Salesforce", ticker: "CRM", domain: "salesforce.com" },
  { name: "Coca-Cola", ticker: "KO", domain: "coca-cola.com" },
  { name: "PepsiCo", ticker: "PEP", domain: "pepsico.com" },
  { name: "Thermo Fisher", ticker: "TMO", domain: "thermofisher.com" },
  { name: "Adobe", ticker: "ADBE", domain: "adobe.com" },
  { name: "Netflix", ticker: "NFLX", domain: "netflix.com" },
  { name: "Accenture", ticker: "ACN", domain: "accenture.com" },
  { name: "Cisco Systems", ticker: "CSCO", domain: "cisco.com" },
  { name: "McDonald's", ticker: "MCD", domain: "mcdonalds.com" },
  { name: "Broadcom", ticker: "AVGO", domain: "broadcom.com" },
  { name: "Disney", ticker: "DIS", domain: "disney.com" },
  { name: "Nike", ticker: "NKE", domain: "nike.com" },
  { name: "Intel", ticker: "INTC", domain: "intel.com" },
  { name: "Goldman Sachs", ticker: "GS", domain: "goldmansachs.com" },
  { name: "Morgan Stanley", ticker: "MS", domain: "morganstanley.com" },
  { name: "IBM", ticker: "IBM", domain: "ibm.com" },
  { name: "Caterpillar", ticker: "CAT", domain: "caterpillar.com" },
  { name: "American Express", ticker: "AXP", domain: "americanexpress.com" },
  { name: "Boeing", ticker: "BA", domain: "boeing.com" },
  { name: "Honeywell", ticker: "HON", domain: "honeywell.com" },
  { name: "Oracle", ticker: "ORCL", domain: "oracle.com" },
  { name: "PayPal", ticker: "PYPL", domain: "paypal.com" },
  { name: "ServiceNow", ticker: "NOW", domain: "servicenow.com" },
  { name: "Intuit", ticker: "INTU", domain: "intuit.com" },
  { name: "Starbucks", ticker: "SBUX", domain: "starbucks.com" },
  { name: "General Electric", ticker: "GE", domain: "ge.com" },
  { name: "3M", ticker: "MMM", domain: "3m.com" },
  { name: "Uber", ticker: "UBER", domain: "uber.com" },
  { name: "Deere & Company", ticker: "DE", domain: "deere.com" },
  { name: "Target", ticker: "TGT", domain: "target.com" },
  { name: "Lockheed Martin", ticker: "LMT", domain: "lockheedmartin.com" },
  { name: "Raytheon", ticker: "RTX", domain: "rtx.com" },
  { name: "BlackRock", ticker: "BLK", domain: "blackrock.com" },
  { name: "Citigroup", ticker: "C", domain: "citigroup.com" },
  { name: "Wells Fargo", ticker: "WFC", domain: "wellsfargo.com" },
  { name: "Bank of America", ticker: "BAC", domain: "bankofamerica.com" },
  { name: "Palantir", ticker: "PLTR", domain: "palantir.com" },
  { name: "Snowflake", ticker: "SNOW", domain: "snowflake.com" },
  { name: "CrowdStrike", ticker: "CRWD", domain: "crowdstrike.com" },
  { name: "Datadog", ticker: "DDOG", domain: "datadoghq.com" },
  { name: "Palo Alto Networks", ticker: "PANW", domain: "paloaltonetworks.com" },
  { name: "Workday", ticker: "WDAY", domain: "workday.com" },
  { name: "Atlassian", ticker: "TEAM", domain: "atlassian.com" },
  { name: "Twilio", ticker: "TWLO", domain: "twilio.com" },
  { name: "HubSpot", ticker: "HUBS", domain: "hubspot.com" },
  { name: "Shopify", ticker: "SHOP", domain: "shopify.com" },
  { name: "Square (Block)", ticker: "SQ", domain: "block.xyz" },
  { name: "Zoom", ticker: "ZM", domain: "zoom.us" },
  { name: "DocuSign", ticker: "DOCU", domain: "docusign.com" },
  { name: "Fortinet", ticker: "FTNT", domain: "fortinet.com" },
  { name: "Autodesk", ticker: "ADSK", domain: "autodesk.com" },
  { name: "Splunk", ticker: "SPLK", domain: "splunk.com" },
  { name: "VMware", ticker: "VMW", domain: "vmware.com" },
  { name: "Akamai", ticker: "AKAM", domain: "akamai.com" },
  { name: "MongoDB", ticker: "MDB", domain: "mongodb.com" },
  { name: "Confluent", ticker: "CFLT", domain: "confluent.io" },
  { name: "Elastic", ticker: "ESTC", domain: "elastic.co" },
  { name: "Okta", ticker: "OKTA", domain: "okta.com" },
  { name: "Zscaler", ticker: "ZS", domain: "zscaler.com" },
  { name: "SentinelOne", ticker: "S", domain: "sentinelone.com" },
  { name: "Cloudflare", ticker: "NET", domain: "cloudflare.com" },
  { name: "Nutanix", ticker: "NTNX", domain: "nutanix.com" },
  { name: "Veeva Systems", ticker: "VEEV", domain: "veeva.com" },
  { name: "Dynatrace", ticker: "DT", domain: "dynatrace.com" },
  { name: "HashiCorp", ticker: "HCP", domain: "hashicorp.com" },
  { name: "GitLab", ticker: "GTLB", domain: "gitlab.com" },
  { name: "Asana", ticker: "ASAN", domain: "asana.com" },
  { name: "Monday.com", ticker: "MNDY", domain: "monday.com" },
  { name: "Freshworks", ticker: "FRSH", domain: "freshworks.com" },
  { name: "ZoomInfo", ticker: "ZI", domain: "zoominfo.com" },
  { name: "ClearGov", ticker: "", domain: "cleargov.com" },
  { name: "Deloitte", ticker: "", domain: "deloitte.com" },
  { name: "McKinsey", ticker: "", domain: "mckinsey.com" },
  { name: "BCG", ticker: "", domain: "bcg.com" },
  { name: "Bain & Company", ticker: "", domain: "bain.com" },
  { name: "KPMG", ticker: "", domain: "kpmg.com" },
  { name: "PwC", ticker: "", domain: "pwc.com" },
  { name: "EY", ticker: "", domain: "ey.com" },
  { name: "Gartner", ticker: "IT", domain: "gartner.com" },
  { name: "Forrester", ticker: "FORR", domain: "forrester.com" },
];

export function searchCompanies(query: string, limit = 10): CompanyEntry[] {
  if (!query.trim()) return companies.slice(0, limit);
  const q = query.toLowerCase().trim();
  return companies
    .filter((c) => c.name.toLowerCase().includes(q) || c.ticker.toLowerCase().includes(q) || c.domain.toLowerCase().includes(q))
    .slice(0, limit);
}

export function getLogoUrl(domain: string): string {
  return `https://logo.clearbit.com/${domain}`;
}
